// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_docs from "./routes/api/docs.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $gogirlgala_index from "./routes/gogirlgala/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $PortfolioCards from "./islands/PortfolioCards.tsx";
import * as $WoodcutIllustrations from "./islands/WoodcutIllustrations.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/docs.ts": $api_docs,
    "./routes/api/joke.ts": $api_joke,
    "./routes/gogirlgala/index.tsx": $gogirlgala_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Header.tsx": $Header,
    "./islands/PortfolioCards.tsx": $PortfolioCards,
    "./islands/WoodcutIllustrations.tsx": $WoodcutIllustrations,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
