// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_gogirlgala_index from "./routes/_gogirlgala/index.tsx";
import * as $admin_analytics from "./routes/admin/analytics.tsx";
import * as $api_analytics from "./routes/api/analytics.ts";
import * as $api_analytics_data from "./routes/api/analytics/data.ts";
import * as $api_docs from "./routes/api/docs.ts";
import * as $index from "./routes/index.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $resume from "./routes/resume.tsx";
import * as $square_terminals from "./routes/square-terminals.tsx";
import * as $AnalyticsDashboard from "./islands/AnalyticsDashboard.tsx";
import * as $AnalyticsTracker from "./islands/AnalyticsTracker.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $PortfolioCards from "./islands/PortfolioCards.tsx";
import * as $ResumeContent from "./islands/ResumeContent.tsx";
import * as $ResumeViewer from "./islands/ResumeViewer.tsx";
import * as $WoodcutEfficient from "./islands/WoodcutEfficient.tsx";
import * as $WoodcutIllustrations_old from "./islands/WoodcutIllustrations.old.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_gogirlgala/index.tsx": $_gogirlgala_index,
    "./routes/admin/analytics.tsx": $admin_analytics,
    "./routes/api/analytics.ts": $api_analytics,
    "./routes/api/analytics/data.ts": $api_analytics_data,
    "./routes/api/docs.ts": $api_docs,
    "./routes/index.tsx": $index,
    "./routes/projects.tsx": $projects,
    "./routes/resume.tsx": $resume,
    "./routes/square-terminals.tsx": $square_terminals,
  },
  islands: {
    "./islands/AnalyticsDashboard.tsx": $AnalyticsDashboard,
    "./islands/AnalyticsTracker.tsx": $AnalyticsTracker,
    "./islands/Header.tsx": $Header,
    "./islands/PortfolioCards.tsx": $PortfolioCards,
    "./islands/ResumeContent.tsx": $ResumeContent,
    "./islands/ResumeViewer.tsx": $ResumeViewer,
    "./islands/WoodcutEfficient.tsx": $WoodcutEfficient,
    "./islands/WoodcutIllustrations.old.tsx": $WoodcutIllustrations_old,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
